//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('players')
export class playersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  playerId: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  email: string;

  @Column('real', { nullable: true })
  totalEarnings: number;

  @Column('text', { nullable: true })
  withdrawalDetails: string;
}
