//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('tournaments')
export class tournamentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  tournamentId: number;

  @Column('text', { nullable: true })
  tournamentName: string;

  @Column('date', { nullable: true })
  startDate: Date;

  @Column('date', { nullable: true })
  endDate: Date;

  @Column('real', { nullable: true })
  entryFee: number;

  @Column('real', { nullable: true })
  prizePool: number;

  @Column('text', { nullable: true })
  status: string;
}
