//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    players: {
      name: 'Players',
      fields: {
        playerId: 'Player Id',
        name: 'Name',
        email: 'Email',
        totalEarnings: 'Total Earnings',
        withdrawalDetails: 'Withdrawal Details',
        id: 'id',
      },
    },
    tournaments: {
      name: 'Tournaments',
      fields: {
        tournamentId: 'Tournament Id',
        tournamentName: 'Tournament Name',
        startDate: 'Start Date',
        endDate: 'End Date',
        entryFee: 'Entry Fee',
        prizePool: 'Prize Pool',
        status: 'Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    players: {
      name: 'Players (fr)',
      fields: {
        playerId: 'Player Id (fr)',
        name: 'Name (fr)',
        email: 'Email (fr)',
        totalEarnings: 'Total Earnings (fr)',
        withdrawalDetails: 'Withdrawal Details (fr)',
        id: 'id',
      },
    },
    tournaments: {
      name: 'Tournaments (fr)',
      fields: {
        tournamentId: 'Tournament Id (fr)',
        tournamentName: 'Tournament Name (fr)',
        startDate: 'Start Date (fr)',
        endDate: 'End Date (fr)',
        entryFee: 'Entry Fee (fr)',
        prizePool: 'Prize Pool (fr)',
        status: 'Status (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
